web/todos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # post views
    path("create", views.ToDoTaskCreateView.as_view(), name="todocreate"),
    path("list", views.ToDoListView.as_view(), name="todolist"),
    path("check/<int:todo_id>", views.todo_check, name="todocheck"),
    path("delete/<int:todo_id>", views.todo_delete, name="tododelete"),
    path("detail/<int:pk>", views.ToDoTaskDetailView.as_view(), name="tododetail"),
    path("update/<int:pk>", views.todo_task_update_view, name="todoupdate"),
]

web/web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("todo/", include("todos.urls")),
    path("habits/", include("habits.urls")),
    path("spacedlearning/", include("spacedlearning.urls")),
]

web/webapp/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

web/core/models.py
"""
Django models
"""

import datetime
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.postgres.fields import ArrayField
from django.db.models import Q
import habits.models
from api.control import get_grade


class Account(models.Model):
    """Model extends base user model"""

    GENDER = [("M", "MALE"), ("F", "FEMALE"), ("O", "OTHER")]
    # Нумерация с нуля
    Q1 = [(i, i) for i in range(4)]
    Q2 = [(i, i) for i in range(16)]
    Q3 = [(i, i) for i in range(20)]

    user = models.OneToOneField(
        get_user_model(), on_delete=models.CASCADE, related_name="account"
    )
    birthday = models.DateField()
    gender = models.CharField(max_length=1, choices=GENDER, default="O")
    q1 = models.IntegerField(default=0, choices=Q1)
    q2 = ArrayField(models.IntegerField(choices=Q2), default=list)
    q3 = ArrayField(models.IntegerField(choices=Q3), default=list)

    @property
    def get_completed_todos_count(self):
        return self.user.todotasks.filter(completed_at=datetime.date.today()).count()

    @property
    def get_skipped_todos_count(self):
        return self.user.todotasks.filter(
            Q(notification_date=datetime.date.today()) & Q(completed_at__isnull=True)
        ).count()

    @property
    def get_completed_habits_count(self):
        return habits.models.HabitDailyRecord.objects.filter(
            habit__user=self.user, date_completed=datetime.date.today()
        ).count()

    @property
    def get_skipped_habits_count(self):
        return (
            habits.models.Habit.objects.filter(
                user=self.user, is_done=False, is_suggested=False
            ).count()
            - self.get_completed_habits_count
            + habits.models.HabitDailyRecord.objects.filter(
                date_completed=datetime.date.today(),
                habit__is_done=True,
                habit__user=self.user,
            ).count()
        )

    @property
    def get_completed_sl_count(self):
        return self.user.spacedlearningtasks.filter(
            prev_train_date=datetime.date.today()
        ).count()

    @property
    def get_skipped_sl_count(self):
        return self.user.spacedlearningtasks.filter(
            next_train_date=datetime.date.today(), is_finished=False
        ).count()

    @property
    def get_grade(self):
        return get_grade(
            self.get_completed_sl_count,
            self.get_completed_todos_count,
            self.get_completed_habits_count,
            self.get_skipped_sl_count
            + self.get_skipped_todos_count
            + self.get_skipped_habits_count,
            list(
                self.user.events.filter(created_at=datetime.date.today()).values_list(
                    "type", flat=True
                )
            ),
        )

    @property
    def get_age(self):
        return int((datetime.date.today() - self.birthday).days / 365)


class Event(models.Model):
    EVENT_TYPE = [
        (0, "Concert/Cinema/Theater"),
        (1, "Work or School"),
        (2, "Planned meeting with friends, co-workers"),
        (3, "Quality time in relationship"),
        (4, "Unplanned meeting after work/school"),
    ]

    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="events"
    )
    title = models.CharField(max_length=128)
    type = models.IntegerField(choices=EVENT_TYPE, default=4)
    created_at = models.DateField(auto_now_add=True)

web/todos/models.py
from django.contrib.auth import get_user_model
from django.db import models


class ToDoTag(models.Model):
    """Model representing a tag for ToDoTask."""

    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="todotags"
    )
    title = models.CharField(max_length=32)
    emoji = models.CharField(max_length=1)


class ToDoTask(models.Model):
    """Model representing a ToDoTask."""

    PRIORITY_LEVEL = (
        (0, "No Priority"),
        (1, "Low Priority"),
        (2, "Medium Priority"),
        (3, "High Priority"),
    )
    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="todotasks"
    )
    title = models.CharField(max_length=128)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateField(null=True)
    notification_date = models.DateTimeField(null=True)
    tags = models.ManyToManyField(ToDoTag, related_name="tasks", blank=True)
    priority_level = models.IntegerField(default=0, choices=PRIORITY_LEVEL)
    is_done = models.BooleanField(default=False)

web/todos/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from . import models


class TagMultipleChoiceField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, tag: models.ToDoTag):
        return f"{tag.emoji}: {tag.title}"


class ToDoTaskForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        super(ToDoTaskForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit("submit", "Create task"))
        self.fields["tags"].queryset = models.ToDoTag.objects.filter(
            user=self.request.user
        )

    class Meta:
        model = models.ToDoTask
        fields = ("title", "description", "notification_date", "tags", "priority_level")

    tags = TagMultipleChoiceField(
        queryset=None, widget=forms.CheckboxSelectMultiple, required=False
    )
    notification_date = forms.DateField(
        label="Notification date", widget=forms.DateInput(attrs={"type": "date"})
    )

web/todos/views.py
import datetime
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views.generic import ListView, DetailView

from . import models
from . import forms


# Create your views here.
class ToDoTaskCreateView(LoginRequiredMixin, CreateView):
    model = models.ToDoTask
    form_class = forms.ToDoTaskForm
    template_name = "todos/todocreate.html"

    success_url = reverse_lazy("todolist")

    def get_form_kwargs(self):
        kwargs = super(ToDoTaskCreateView, self).get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.save()
        return redirect(self.success_url)


class ToDoListView(LoginRequiredMixin, ListView):
    template_name = "todos/todolist.html"
    context_object_name = "todo_list"

    def get_queryset(self):
        return models.ToDoTask.objects.filter(user=self.request.user).order_by(
            "-notification_date"
        )


@login_required
def todo_check(request, todo_id):
    todo = get_object_or_404(models.ToDoTask, pk=todo_id)
    if todo.user != request.user:
        return Http404()
    if todo.is_done:
        todo.is_done = False
        todo.completed_at = None
    else:
        todo.is_done = True
        todo.completed_at = datetime.date.today()
    todo.save()

    return redirect("todolist")


@login_required
def todo_delete(request, todo_id):
    todo = get_object_or_404(models.ToDoTask, pk=todo_id)
    if todo.user != request.user:
        return Http404()
    todo.delete()
    return redirect("todolist")


class ToDoTaskDetailView(LoginRequiredMixin, DetailView):
    model = models.ToDoTask
    template_name = "todos/tododetails.html"

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return models.ToDoTask.objects.filter(user=self.request.user)
        else:
            return models.ToDoTask.none()


@login_required
def todo_task_update_view(request, pk):
    obj = get_object_or_404(models.ToDoTask, id=pk)
    if obj.user != request.user:
        return Http404()
    if request.method == "POST":
        form = forms.ToDoTaskForm(request.POST, instance=obj, request=request)
        if form.is_valid():
            form.save()
            return redirect("todolist")
    form = forms.ToDoTaskForm(instance=obj, request=request)
    return render(request, "todos/todocreate.html", {"form": form})

web/todos/templates/todos/todays_feed.html
{% extends "base.html" %}
{% block title %}Today's feed{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <h1>Today's feed</h1>
    <hr>

    <!-- Today's performance -->
    <div class="card text-center">
      <div class="card-header">
        <h2>Assessing your today's performance</h2>
      </div>
      <div class="card-body">
        <h3 class="card-title">You scored {{ score }} out of 10</h3>
        <p class="card-text">Well done!</p>
      </div>
      <div class="card-footer text-muted">
        last updated: now
      </div>
    </div>

    <div class="card-group">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Completed TODOs: {{ completed_todos }}</h5>
          <h5 class="card-title">Due today left TODOs: {{ skipped_todos }}</h5>
          <p class="card-text">Well done!</p>
        </div>
      </div>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Completed Habits: {{ completed_habits }}</h5>
          <h5 class="card-title">Due today left Habits: {{ skipped_habits }}</h5>
          <p class="card-text">Well done!</p>
        </div>
      </div>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Completed SpaceLearning tasks: {{ completed_sl }}</h5>
          <h5 class="card-title">Due today left SpaceLearning tasks: {{ skipped_sl }}</h5>
          <p class="card-text">Well done!</p>
        </div>
      </div>
    </div>

    <hr>
    <!-- Events -->
    <h2>What events did you attend today?</h2>
    <h5>Add new event to the list</h5>
    {% csrf_token %}
    {% crispy form form.helper %}

    <h5>Today's events</h5>
    <ul class="list-group">
    {% for event in events %}
      <li class="list-group-item">{{ event.title }}<span class="badge badge-secondary">{{ event.get_type_display }}</span></li>
    {% endfor %}
    </ul>


{% endblock %}

web/todos/templates/todos/todocreate.html
{% extends 'base.html' %}
{% block title %}ToDoTask Create{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <h1>ToDoTask Create</h1>
        {% csrf_token %}
        {% crispy form form.helper %}
{% endblock %}

web/todos/templates/todos/tododetails.html
{% extends "base.html" %}
{% block title %}{{ object.title }}{% endblock %}

{% block content %}
    <h1>{{ object.title }}</h1>
    <div class="form-group row">
        <label for="staticTitle" class="col-sm-2 col-form-label">Title</label>
        <div class="col-sm-10">
          <input type="text" readonly class="form-control-plaintext" id="staticTitle" value="{{ object.title }}">
        </div>
    </div>
    <div class="form-group row">
        <label for="staticDescription" class="col-sm-2 col-form-label">Description</label>
        <div class="col-sm-10">
          <input type="text" readonly class="form-control-plaintext" id="staticDescription" value="{{ object.description }}">
        </div>
    </div>
    <div class="form-group row">
        <label for="staticNotificationDate" class="col-sm-2 col-form-label">Deadline date</label>
        <div class="col-sm-10">
          <input type="text" readonly class="form-control-plaintext" id="staticNotificationDate" value="{{ object.notification_date }}">
        </div>
    </div>
    <div class="form-group row">
        <label for="staticPriorityLevel" class="col-sm-2 col-form-label">PriorityLevel</label>
        <div class="col-sm-10">
          <input type="text" readonly class="form-control-plaintext" id="staticPriorityLevel " value="{{ object.get_priority_level_display }}">
        </div>
    </div>
    <div class="form-group row">
        <label for="staticIsDone" class="col-sm-2 col-form-label">IsDone</label>
        <div class="col-sm-10">
          <input type="text" readonly class="form-control-plaintext" id="staticIsDone" value="{{ object.is_done }}">
        </div>
    </div>


    <form method="post" action="{% url "todoupdate" object.id %}">
        {% csrf_token %}
        <button onclick="this.form.submit()" class="btn btn-primary btn-lg btn-block">Change ToDo info</button>
    </form>


{% endblock %}

web/todos/templates/todos/todolist.html
{% extends "base.html" %}
{% block title %}ToDo{% endblock %}

{% block content %}
<h1>ToDo List</h1>


<hr>
    <ul class="list-group">
        <a href="{% url 'todocreate' %}" class="btn btn-info" type="button">Add new ToDo</a>
        {% if todo_list|length == 0 %}<hr><h3>There are no ToDos for now.<hr> Click the button below to add ToDo.</h3></hr>{% endif %}
        {% for todo in todo_list %}
            {% csrf_token %}
                <li class="list-group-item list-group-item-action {% if todo.priority_level == 1 %}list-group-item-light{% elif todo.priority_level == 2 %}list-group-item-info{% elif todo.priority_level == 3 %}list-group-item-warning{% endif %}">
                    <div class="form-check">
                        <form method="post" action="{% url "todocheck" todo.id %}">
                            {% csrf_token %}
                            <input class="form-check-input" type="checkbox" value="" id=""
                                   {% if todo.is_done %}checked{% endif %}
                                   title="{% if not todo.is_done %} mark as done {% else %} mark undone {% endif %}"
                                   onchange="this.form.submit()"
                                   name="is_done">
                            <label class="form-check-label" for="flexcheckchecked">
                                {{ todo.title }}
                            </label>
                            <a class="btn btn-primary" href="{% url 'tododetail' todo.pk %}" role="button" title="details">details</a>
                            <a class="btn btn-primary" href="{% url 'tododelete' todo.id %}" role="button" title="delete">delete</a>
                        </form>
                    </div>
                </li>
        {% endfor %}
    </ul>
</hr>
{% endblock %}